name: test-docs

on:
  pull_request:
    branches: [main]

jobs:
  test-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
      - name: Build Docusaurus website
        run: |
          npm ci 
          npm run doc:build
